### ISSUE TITLE
invite only does not seem to work?

### ISSUE THREAD

**Issue by lucletruc** [rchatham/PeerConnectivity#2]
How do you call the viewcontroller for searching advertisers with the inviteOnly option? it's kind of unclear to me. Just setting the connection type to inviteOnly and then writing pcm.start does not seem to change anything :(

**Comment by rchatham** [comment]
You should call `pcm.browserViewController(_ callback: @escaping (PeerBrowserViewControllerEvent)->Void) -> UIViewController?` after calling `start()`. The `.InviteOnly` connection type requires you to present this interface or create your own for adding new members to a session. Only the `.Automatic` connection type will add available new members whenever calling `start()`.

http://reidchatham.com/docs/PeerConnectivity/Classes/PeerConnectionManager.html#/s:FC16PeerConnectivity21PeerConnectionManager21browserViewControllerFFOS_30PeerBrowserViewControllerEventT_GSqCSo16UIViewController_

**Comment by rchatham** [comment]
@lucletruc closing this issue. If you have any further questions about this feel free to reopen.
