### ISSUE TITLE
intermittent crashing

### ISSUE THREAD

**Issue by Nathan187** [rchatham/PeerConnectivity#3]
Been using this library and it works fine.  However, I am getting intermittent errors that cause it to crash.  Below is a sample of the crash report

6   PeerConnectivity              	0x00000001013449d8 0x101338000 + 51672
7   PeerConnectivity              	0x000000010134ab1c 0x101338000 + 76572
8   PeerConnectivity              	0x000000010134b4b4 0x101338000 + 79028
9   PeerConnectivity              	0x0000000101356e48 0x101338000 + 126536
10  PeerConnectivity              	0x000000010134b2c4 0x101338000 + 78532
11  PeerConnectivity              	0x0000000101343164 0x101338000 + 45412
12  PeerConnectivity              	0x000000010134ab1c 0x101338000 + 76572
13  PeerConnectivity              	0x000000010134b4b4 0x101338000 + 79028
14  PeerConnectivity              	0x0000000101353a2c 0x101338000 + 113196
15  PeerConnectivity              	0x0000000101353010 0x101338000 + 110608
16  MultipeerConnectivity         	0x00000001a1bdf02c __58-[MCSession syncHandleNetworkEvent:pid:freeEventWhenDone:]_block_invoke.630 + 144

i can't isolate where in the code it's happening.  i've seen similar postings like this.  seemed to be around the MCSession synchandleNetworkEvent call

any insight would really help.

**Comment by rchatham** [comment]
Hey Nathan, great to hear that you like the library. It looks like that might be an error in the MultipeerConnectivity framework from Apple. Can you provide more context into what is happening?

**Comment by nboyd-sportdx** [comment]
reid, i wanted to take a few minutes to thank you for your library.  i used it in an app for our company.  it worked extremely well.  basically, when data is captured on one tablet....other tablets that are listening...they get the same exact data.   i can't elaborate too much but just wanted to let you know that something you made is being used and it performs well

**Comment by rchatham** [comment]
Awesome to hear @nboyd-sportdx! I'm so glad this is working well for you. Is the crash still affecting you @Nathan187.
