### ISSUE TITLE
xcode 9 / 3.2

### ISSUE THREAD

**Issue by Nathan187** [rchatham/PeerConnectivity#4]
does this work for swift 3.2?   i am using carthage and I get a:

Build Failed
	Task failed with exit code 65:

thanks for any help

**Comment by swaterfall** [comment]
@rchatham Any plans to fix this? Seems like just a change to some delegates.

**Comment by rchatham** [comment]
Hey! Sorry for the slow response here. I can possibly try to get to this tonight or if you'd prefer to make a pull request I'd be happy take a look. Should be fairly straightforward.

**Comment by rchatham** [comment]
Hey @Nathan187, @swaterfall! Check out this branch here and see if that works for you. https://github.com/rchatham/PeerConnectivity/tree/swift-3.2

**Comment by swaterfall** [comment]
@rchatham yup works great thanks!

**Comment by Nathan187** [comment]
@rchatham yes!  works for me as well.  thank you for your efforts

**Comment by ericwastaken** [comment]
@rchatham - confirming branch swift-3.2 worked for me as well. Thanks for this change!

**Comment by rchatham** [comment]
Awesome! Thanks everyone. I will post a new version to Cocoapods soon for convenience.
