### ISSUE TITLE
Can't connect (ICE + FAILED BINDING)

### ISSUE THREAD

**Issue by Luccifer** [rchatham/PeerConnectivity#5]
Hi there! Spent a lot of time on trying to resolve the problem, the code is actually here: 
https://gist.github.com/Luccifer/5e588502992124a1b0ec184361bfcd4c

Log: https://gist.github.com/Luccifer/60e55e17507012793c8b6d412bf5e9f4

Help please, I googled it and people usually turning off the encryption, but this didn't help, I have already tried to change it in sources of Pod..

**Comment by rchatham** [comment]
This is an issue in the implementation, not the Pod. It actually says that the framework even connected in your logs. Try using `.automatic` and specifying a service string if you want it to connect to everyone with that same service string nearby.

**Comment by Luccifer** [comment]
That's the problem, wanna make it by invite only, the app is planned to be used in crowed places with same app on many devices

**Comment by rchatham** [comment]
@Luccifer Sorry for not getting back to you about this sooner! This is definitely possible but may require a custom invite implementation for your use case. Invite only can be accomplished by using the the browser view controller which you can get from the `PeerConnectionManager` when using the `.inviteOnly` option or by implementing your own custom rules for accepting an invitation through the framework.

Look into passing context information when you invite a user and creating some kind of view to display the available users for invite from the `foundUsers` property. Then the person receiving the invite can be alerted to the invite and can decide if they want to join the session based on the context information that is sent by the first user.

Check out the playground for an example.
